folly_sources = \
  ./include/folly/Foreach.h \
  ./include/folly/FBVector.h \
  ./include/folly/CppAttributes.h \
  ./include/folly/AtomicHashArray.h \
  ./include/folly/AtomicHashMap-inl.h \
  ./include/folly/FileUtil.cpp \
  ./include/folly/IndexedMemPool.h \
  ./include/folly/AtomicStruct.h \
  ./include/folly/Traits.h \
  ./include/folly/Logging.h \
  ./include/folly/Bits.cpp \
  ./include/folly/AtomicHashArray-inl.h \
  ./include/folly/CPortability.h \
  ./include/folly/portability/PThread.h \
  ./include/folly/portability/SysFile.h \
  ./include/folly/portability/Asm.h \
  ./include/folly/portability/SysTypes.h \
  ./include/folly/portability/Constexpr.h \
  ./include/folly/portability/Time.cpp \
  ./include/folly/portability/SysUio.h \
  ./include/folly/portability/SysMman.cpp \
  ./include/folly/portability/Unistd.h \
  ./include/folly/portability/Sockets.cpp \
  ./include/folly/portability/Sockets.h \
  ./include/folly/portability/Fcntl.cpp \
  ./include/folly/portability/Time.h \
  ./include/folly/portability/IOVec.h \
  ./include/folly/portability/SysFile.cpp \
  ./include/folly/portability/Windows.h \
  ./include/folly/portability/Fcntl.h \
  ./include/folly/portability/Config.h \
  ./include/folly/portability/SysMman.h \
  ./include/folly/portability/SysUio.cpp \
  ./include/folly/portability/Unistd.cpp \
  ./include/folly/ThreadLocal.h \
  ./include/folly/Exception.h \
  ./include/folly/ScopeGuard.h \
  ./include/folly/SpookyHashV1.cpp \
  ./include/folly/FormatTraits.h \
  ./include/folly/detail/BitsDetail.h \
  ./include/folly/detail/Sleeper.h \
  ./include/folly/detail/Futex.cpp \
  ./include/folly/detail/CacheLocality.h \
  ./include/folly/detail/CacheLocality.cpp \
  ./include/folly/detail/FunctionalExcept.h \
  ./include/folly/detail/FunctionalExcept.cpp \
  ./include/folly/detail/MemoryIdler.h \
  ./include/folly/detail/ThreadLocalDetail.h \
  ./include/folly/detail/UncaughtExceptionCounter.h \
  ./include/folly/detail/AtomicHashUtils.h \
  ./include/folly/detail/StaticSingletonManager.h \
  ./include/folly/detail/MemoryIdler.cpp \
  ./include/folly/detail/StaticSingletonManager.cpp \
  ./include/folly/detail/Futex.h \
  ./include/folly/detail/ThreadLocalDetail.cpp \
  ./include/folly/detail/Malloc.h \
  ./include/folly/detail/BitIteratorDetail.h \
  ./include/folly/detail/FileUtilDetail.h \
  ./include/folly/ThreadCachedInt.h \
  ./include/folly/ProducerConsumerQueue.h \
  ./include/folly/Portability.h \
  ./include/folly/LifoSem.h \
  ./include/folly/LifoSem.cpp \
  ./include/folly/FileUtil.h \
  ./include/folly/Malloc.h \
  ./include/folly/Preprocessor.h \
  ./include/folly/AtomicHashMap.h \
  ./include/folly/Hash.h \
  ./include/folly/Likely.h \
  ./include/folly/SpookyHashV2.h \
  ./include/folly/SpookyHashV1.h \
  ./include/folly/MicroSpinLock.h \
  ./include/folly/CpuId.h \
  ./include/folly/ApplyTuple.h \
  ./include/folly/SpookyHashV2.cpp \
  ./include/folly/Bits.h \
  ./include/folly/Baton.h
contentious_sources = \
  ./contentious/bp_vector-impl.h \
  ./contentious/cont_vector.h \
  ./contentious/threadpool.h \
  ./contentious/contentious_constants.h \
  ./contentious/bp_vector_iterator.h \
  ./contentious/cont_vector-impl.h \
  ./contentious/threadpool.cc \
  ./contentious/bp_vector_base-impl.h \
  ./contentious/contentious.cc \
  ./contentious/bp_vector_glob.cc \
  ./contentious/util.h \
  ./contentious/tr_vector-impl.h \
  ./contentious/contentious.h \
  ./contentious/bp_vector_constants.h \
  ./contentious/bp_vector.h
runner_sources = \
  ./tests/cont_vector-tests.cc \
  ./tests/bp_vector-tests.h \
  ./tests/reduce-tests.cc \
  ./tests/bp_vector-tests.cc \
  ./tests/cont_vector-tests.h \
  ./tests/reduce-tests.h \
  ./tests/format.cc \
  ./tests/slbench.h \
  ./tests/runner.cc
